@startuml
'https://plantuml.com/state-diagram
hide empty description

title States of HtmlDocument

[*] -right-> Downloaded : get
Downloaded -right-> Analyzed : analyze
Downloaded : URI, HTML code, and\ndownloaded at were set
Analyzed -right-> [*] : delete
Analyzed : title, created at, authors, link URIs, and\nimages URIs were extracted and set

@enduml
